In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
os.listdir()

['wrangling.ipynb',
 'filtered_data.csv',
 'User_Part3.txt',
 '.ipynb_checkpoints']

In [4]:
dat = pd.read_csv("User_Part3.txt",header=None)

In [5]:
dat.describe()

,0,1,2,3,4,5,6,7,8,9,...,163,164,165,166,167,168,169,170,171,172
count,351087.000000,351087.000000,351087.000000,351087.000000,351087.000000,351087.000000,302225.0,302225.000000,302225.000000,142445.000000,...,325643.000000,325643.000000,325643.000000,25242.000000,1431.000000,107484.000000,107484.000000,107484.000000,259556.000000,351088.000000
mean,0.000330,0.001988,0.009770,0.000185,0.001473,0.006429,0.0,0.000026,0.000255,2.850588,...,0.009123,0.060744,0.268472,4.518087,4.527638,0.015519,0.096396,0.454514,0.300949,175543.500000
std,0.018174,0.044544,0.098358,0.013605,0.038346,0.079921,0.0,0.005145,0.015960,4.514317,...,0.146110,0.458963,1.203567,0.725514,0.761258,0.223772,0.576420,1.886261,0.458671,101350.519992
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,4.000000,4.000000,0.000000,0.000000,0.000000,0.000000,87771.750000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.000000,...,0.000000,0.000000,0.000000,5.000000,5.000000,0.000000,0.000000,0.000000,0.000000,175543.500000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,5.000000,5.000000,0.000000,0.000000,0.000000,1.000000,263315.250000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,690.000000,...,24.000000,72.000000,171.000000,5.000000,5.000000,33.000000,67.000000,281.000000,1.000000,351087.000000

In [6]:
# rename columns
cols = []
for i in dat.columns:
    cols.append("var"+str(i))
dat.columns = cols
dat.rename(columns={"var171":"target","var172":"id"},inplace=True)

In [7]:
dat.columns

Index(['var0', 'var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8',
       'var9',
       ...
       'var163', 'var164', 'var165', 'var166', 'var167', 'var168', 'var169',
       'var170', 'target', 'id'],
      dtype='object', length=173)

In [56]:
# select columns

# dat.loc[:,'var0':'var3']
# dat.iloc[:,0:3]
# dat[['var0','var3']]

# select rows
# dat.iloc[0:10,0:3]
# dat.iloc[-1,:]

In [29]:
# filter rows
dat[dat['var1']>0.1]
dat[dat['var9'].notnull() & dat['var1'] > 0.1] # multiple filter criteria

,var0,var1,var2,var3,var4,var5,var6,var7,var8,var9,...,var163,var164,var165,var166,var167,var168,var169,var170,target,id
874,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,193042
1114,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,5.00,NaN,0.0,0.0,1.0,0.0,89730
1488,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,91924
2691,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,162879
4010,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,191741
4817,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,16219
6505,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,36993
7155,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,35545
11100,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,148204
12315,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,3.0,5.00,NaN,0.0,0.0,3.0,0.0,205197
12717,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,148494
17808,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,254451
19029,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,336754
19688,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,334542
19793,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,66772
23114,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,164626
23331,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,157559
23657,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,...,0.0,0.0,2.0,NaN,NaN,2.0,2.0,2.0,0.0,52735
24385,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,251463
28826,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,332374
29243,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,94101
29340,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,61868
30105,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,4.00,NaN,0.0,0.0,0.0,0.0,46390
30377,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,...,0.0,0.0,0.0,4.98,5.00,2.0,14.0,51.0,0.0,83714
31510,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,6.0,NaN,NaN,0.0,0.0,1.0,0.0,104677
31511,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,200806
32180,1.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,275180
37713,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,234372
40123,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,...,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,43308
40298,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,0.0,1.0,1.0,NaN,28846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314376,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,5.00,NaN,0.0,0.0,0.0,0.0,252306
315541,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,3.0,...,0.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,112949
316519,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,130609
317399,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,271937
317721,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,215699
319621,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,220972
321713,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,...,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,203733
323197,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,74862
324922,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,5.00,NaN,0.0,0.0,1.0,0.0,1632
325801,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,4.00,3.66,0.0,0.0,1.0,0.0,130937
326735,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,5.00,NaN,0.0,0.0,1.0,0.0,93821
327378,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,288791
329094,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,NaN,173834
329394,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,1727
330576,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,3.00,NaN,0.0,0.0,0.0,0.0,30375
331819,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,258717
332530,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,181553
335498,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,13.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,114726
336062,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,126160
337292,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,329664
338740,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,197166
339178,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,4.66,NaN,0.0,1.0,3.0,0.0,55244
341313,1.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,...,0.0,0.0,0.0,4.00,NaN,0.0,0.0,0.0,0.0,201247
341596,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,NaN,NaN,0.0,0.0,0.0,0.0,223970
342147,1.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,20147
344555,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,338514
345821,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,149902
348271,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,231957
349287,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,309447
349916,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,53600

In [9]:
# missing values 
dat.isnull().sum() # show how many missing values in each columns

var0           1
var1           1
var2           1
var3           1
var4           1
var5           1
var6       48863
var7       48863
var8       48863
var9      208643
var10     215443
var11     304076
var12     306208
var13     342410
var14     305345
var15     214466
var16     342410
var17     305345
var18     214466
var19     344313
var20     313928
var21     222660
var22     348469
var23     336364
var24     310666
var25     351071
var26     350968
var27     350477
var28     344313
var29     313928
           ...
var143    299193
var144    297818
var145    347922
var146    334781
var147    301484
var148    350374
var149    346566
var150    334047
var151    349509
var152    341740
var153    316847
var154     40732
var155     40732
var156     40732
var157    343261
var158    282685
var159     58866
var160    349119
var161    334227
var162    277107
var163     25445
var164     25445
var165     25445
var166    325846
var167    349657
var168    243604
var169    243604
var170    243604
target     91532
id             0
Length: 173, dtype: int64

In [ ]:
# table in r
dat['var6'].value_counts()

x = np.array([1, 1, 1, 1, 2, 2]);
y = np.array(["a", "a", "b", "a", "a", "b"]);
pd.crosstab(x, y, rownames = ['x'], colnames = ['y']);